.type was changed to .response_type in xpyb 1.3
This fixes the "AttributeError: 'NoExposureEvent' object has no attribute 'type'" error

Next issue: On "EnterNotifyEvent" the type is NoneType and response_type fails on that